name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # 允许手动触发

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录，确保能找到 data 目录
      - name: Install clang-format
        run: sudo apt install -y clang-format curl
      - name: Lint
        run: find src tools -name '*.cc' -o -name '*.h' | xargs clang-format -Werror --dry-run || { echo Please lint your code by '"'"find src tools -name '*.cc' -o -name '*.h' | xargs clang-format -i"'"'.; false; }

  build:
    runs-on: ubuntu-24.04
    needs: lint
    steps:
      - name: Checkout librime
        uses: actions/checkout@v4
        with:
          repository: rime/librime

      - name: Checkout current repository with full history
        uses: actions/checkout@v4
        with:
          path: plugins/predict
          fetch-depth: 0  # 获取完整历史记录

      - name: Install dependency
        run: ./action-install-linux.sh

      - name: Build librime with plugin
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_ASAN=ON
          cmake --build build

      - name: Build predict.db from local data
        working-directory: build/bin
        run: |
          # 从本仓库的 data 目录复制 predict.txt
          cp ../../plugins/predict/data/predict.txt ./
          cat predict.txt | ../plugins/predict/bin/build_predict
          ls -la predict.db  # 确认文件生成

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: predict-db-${{ github.run_id }}-${{ github.run_attempt }}
          release_name: Predict DB (${{ github.sha }})
          draft: false
          prerelease: false
          body: |
            Auto-generated predict.db from CI build
            - Commit: ${{ github.sha }}
            - Run ID: ${{ github.run_id }}

      - name: Upload predict.db to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/bin/predict.db
          asset_name: predict.db
          asset_content_type: application/octet-stream

      - name: Upload predict.txt to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/bin/predict.txt
          asset_name: predict.txt
          asset_content_type: text/plain

      - name: Upload Artifact (backup)
        uses: actions/upload-artifact@v4
        with:
          name: predict-db-${{ github.run_id }}
          path: |
            build/bin/predict.db
            build/bin/predict.txt
