name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt install -y clang-format curl
      - name: Lint
        run: find src tools -name '*.cc' -o -name '*.h' | xargs clang-format -Werror --dry-run || { echo Please lint your code by '"'"find src tools -name '*.cc' -o -name '*.h' | xargs clang-format -i"'"'.; false; }

  build:
    runs-on: ubuntu-24.04
    needs: lint
    steps:
      - name: Checkout librime
        uses: actions/checkout@v4
        with:
          repository: rime/librime

      - name: Checkout last commit
        uses: actions/checkout@v4
        with:
          path: plugins/predict

      - name: Install dependency
        run: ./action-install-linux.sh

      - name: Build librime with plugin
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_ASAN=ON
          cmake --build build

      - name: Build predict.db
        working-directory: build/bin
        run: |

          wget -O predict.txt https://github.com/$GITHUB_REPOSITORY/releases/download/predict.txt-0.1/predict.txt
          # wget -O release.db https://github.com/rime/librime-predict/releases/download/data-1.0/predict.db
          cat predict.txt | ../plugins/predict/bin/build_predict
          # diff predict.db release.db

      - name: Create directory and move predict.db
        run: |
          mkdir -p /home/runner/work/librime-predict/librime-predict/build/bin/artifact
          mv /home/runner/work/librime-predict/librime-predict/build/bin/predict.db /home/runner/work/librime-predict/librime-predict/build/bin/artifact/

      - name: Set current time
        id: current-time
        run: echo "CURRENT_TIME=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create release directory
        run: mkdir -p /home/runner/work/librime-predict/librime-predict/build/bin/release

      - name: Move artifact to release directory
        run: mv /home/runner/work/librime-predict/librime-predict/build/bin/artifact /home/runner/work/librime-predict/librime-predict/build/bin/release/librime-predict.db_${{ env.CURRENT_TIME }}

      - name: Upload Release
        # 打包上传生成的文件
        uses: actions/upload-artifact@v4
        with:
          name: "librime-predict.db_${{ env.CURRENT_TIME }}"
          path: /home/runner/work/librime-predict/librime-predict/build/bin/release
